webtalk_init -webtalk_dir C:\\Users\\maslam\\Desktop\\IDLAB\\gitHub\\documents\\Non_PhDworks\\FPGAdesign_com\\Lec5_EMIO_implementation\\vivado\\project_1\\project_1.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Dec 25 02:30:58 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2016.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2016.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "jrm53aiihuhdas57en0nkr5c2f" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2016.2_31" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "31" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1545662837156" -context "sdk\\\\hardware/1545662837156"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1545662837156"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1545662837156"
webtalk_add_data -client sdk -key VivadoVersion -value "2016.2" -context "sdk\\\\hardware/1545662837156"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1545662837156"
webtalk_add_data -client sdk -key Device -value "7z020" -context "sdk\\\\hardware/1545662837156"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1545662837156"
webtalk_add_data -client sdk -key uid -value "1545663011339" -context "sdk\\\\bsp/1545663011339"
webtalk_add_data -client sdk -key hwid -value "1545662837156" -context "sdk\\\\bsp/1545663011339"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1545663011339"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1545663011339"
webtalk_add_data -client sdk -key uid -value "1545663016470" -context "sdk\\\\application/1545663016470"
webtalk_add_data -client sdk -key hwid -value "1545662837156" -context "sdk\\\\application/1545663016470"
webtalk_add_data -client sdk -key bspid -value "1545663011339" -context "sdk\\\\application/1545663016470"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1545663016470"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1545663016470"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1545663016470"
webtalk_transmit -clientid 2353909957 -regid "" -xml C:\\Users\\maslam\\Desktop\\IDLAB\\gitHub\\documents\\Non_PhDworks\\FPGAdesign_com\\Lec5_EMIO_implementation\\vivado\\project_1\\project_1.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Users\\maslam\\Desktop\\IDLAB\\gitHub\\documents\\Non_PhDworks\\FPGAdesign_com\\Lec5_EMIO_implementation\\vivado\\project_1\\project_1.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Users\\maslam\\Desktop\\IDLAB\\gitHub\\documents\\Non_PhDworks\\FPGAdesign_com\\Lec5_EMIO_implementation\\vivado\\project_1\\project_1.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
